# Use the httpd-parent image as base
FROM quay.io/redhattraining/httpd-parent

LABEL io.k8s.description="httpd" \
      io.k8s.displayname="httpd" \
      io.openshift.expose-service="8080:http" \
      io.openshift.tags="apache, httpd"
      
EXPOSE 8080

RUN sed -i "s/Lesten 80/Listen 8080/g" /etc/httpd/conf/httpd.conf
RUN sed -i "s/#ServerName www.example.com:80/ServerName 0.0.0.0:8080/g" /etc/http/conf/http.conf

RUN chgrp -R 0 /var/log/httpd /var/run/httpd && \
    chmod -R g=u /var/log/httpd /var/run/httpd

USER 1001

    

      
